In [307]:
import pandas as pd
import numpy as np
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score,roc_auc_score,confusion_matrix

In [308]:
train = pd.read_csv('C:/Users/HP/Downloads/Selection_sklearn/Machine_Learning_with_Text/pycon-2016-tutorial-master/data/yelp.csv')

In [309]:
X = train['text']
y = train['stars']

In [310]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1)
X_train.shape

(7500,)

In [311]:
y_train.value_counts()

4    2642
5    2505
3    1096
2     693
1     564
Name: stars, dtype: int64

In [345]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(min_df=5,stop_words='english',ngram_range=(1,2),max_df=0.9)

In [346]:
X_train_dtm = vect.fit_transform(X_train)
X_test_dtm = vect.transform(X_test)

In [347]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB(alpha=1)

In [348]:
nb.fit(X_train_dtm,y_train)

MultinomialNB(alpha=1, class_prior=None, fit_prior=True)

In [349]:
pre = nb.predict(X_test_dtm)

In [350]:
accuracy_score(y_test,pre)

0.51719999999999999

In [318]:
X_train_tokens = vect.get_feature_names()

In [319]:
confusion_matrix(y_test,pre)

array([[ 93,  40,  21,  17,  14],
       [ 44,  64,  64,  47,  15],
       [ 20,  24, 109, 161,  51],
       [ 18,  11,  71, 528, 256],
       [ 22,  10,  28, 273, 499]], dtype=int64)

In [320]:
X_test[pre<y_test].head()

2041    I have shared many an awful, hungover morning ...
6111    Does anyone know why their regular subs are $1...
7673    I had a mammogram completed on 12/12/10.  This...
1266    I've never been to this location before. My hu...
2370    Not a bad theater. The staff is friendly and t...
Name: text, dtype: object

In [321]:
X_train_tokens

['00',
 '00 pm',
 '000',
 '00am',
 '00pm',
 '01',
 '05',
 '07',
 '10',
 '10 00',
 '10 11',
 '10 12',
 '10 15',
 '10 30',
 '10 bucks',
 '10 discount',
 '10 min',
 '10 mins',
 '10 minutes',
 '10 people',
 '10 pm',
 '10 seconds',
 '10 times',
 '10 years',
 '100',
 '1000',
 '101',
 '10am',
 '10pm',
 '11',
 '11 00',
 '11 30',
 '110',
 '115',
 '11am',
 '11pm',
 '12',
 '12 30',
 '12 50',
 '12 bucks',
 '120',
 '12oz',
 '13',
 '14',
 '15',
 '15 20',
 '15 bucks',
 '15 min',
 '15 mins',
 '15 minutes',
 '15 years',
 '150',
 '16',
 '160',
 '16th',
 '17',
 '17 years',
 '18',
 '19',
 '19th',
 '19th ave',
 '1pm',
 '1st',
 '1st time',
 '20',
 '20 00',
 '20 25',
 '20 30',
 '20 bucks',
 '20 min',
 '20 minute',
 '20 minutes',
 '20 people',
 '20 times',
 '20 years',
 '200',
 '2004',
 '2006',
 '2007',
 '2009',
 '2010',
 '2011',
 '2012',
 '20s',
 '21',
 '22',
 '23',
 '24',
 '24 hour',
 '24 hours',
 '24th',
 '25',
 '25 minutes',
 '250',
 '26',
 '27',
 '28',
 '29',
 '2am',
 '2nd',
 '2nd time',
 '2pm',
 '30',
 

In [322]:
nb.feature_count_

array([[ 19.,   1.,   5., ...,   0.,   1.,   0.],
       [ 28.,   0.,   2., ...,   0.,   6.,   1.],
       [ 30.,   3.,   2., ...,   2.,   6.,   1.],
       [ 49.,   2.,   3., ...,   9.,   9.,   1.],
       [ 33.,   0.,   7., ...,   8.,  11.,   2.]])

In [323]:
onestarcount = nb.feature_count_[0,:]
twostarcount = nb.feature_count_[1,:]
threestarcount=nb.feature_count_[2,:]
fourstarcount=nb.feature_count_[3,:]
fivestarcount = nb.feature_count_[4,:]

In [324]:
onestarcount

array([ 19.,   1.,   5., ...,   0.,   1.,   0.])

In [325]:
reviews = pd.DataFrame({'Token':X_train_tokens,'1starcount':onestarcount,'2starcount':twostarcount,'3starcount':threestarcount,'4starcount':fourstarcount,'5starcount':fivestarcount}).set_index('Token')

In [326]:
reviews['1starcount']=reviews['1starcount']/nb.class_count_[0]
reviews['2starcount']=reviews['2starcount']/nb.class_count_[1]
reviews['3starcount']=reviews['3starcount']/nb.class_count_[2]
reviews['4starcount']=reviews['4starcount']/nb.class_count_[3]
reviews['5starcount']=reviews['5starcount']/nb.class_count_[4]

In [327]:
reviews['1starcount'] = reviews['1starcount']+1
reviews['2starcount'] = reviews['2starcount']+1
reviews['3starcount'] = reviews['3starcount']+1
reviews['4starcount'] = reviews['4starcount']+1
reviews['5starcount'] = reviews['5starcount']+1

In [328]:
reviews['1starratio']=reviews['1starcount']/(reviews['2starcount']+reviews['3starcount']+reviews['4starcount']+reviews['5starcount'])
reviews['2starratio']=reviews['2starcount']/(reviews['1starcount']+reviews['3starcount']+reviews['4starcount']+reviews['5starcount'])
reviews['3starratio']=reviews['3starcount']/(reviews['1starcount']+reviews['2starcount']+reviews['4starcount']+reviews['5starcount'])
reviews['4starratio']=reviews['4starcount']/(reviews['1starcount']+reviews['2starcount']+reviews['3starcount']+reviews['5starcount'])
reviews['5starratio']=reviews['5starcount']/(reviews['1starcount']+reviews['2starcount']+reviews['3starcount']+reviews['4starcount'])

In [329]:
onestar = reviews[(reviews['1starratio']>reviews['2starratio']) & (reviews['1starratio']>reviews['3starratio']) & (reviews['1starratio']>reviews['4starratio']) & (reviews['1starratio']>reviews['5starratio'])]
twostar = reviews[(reviews['2starratio']>reviews['1starratio']) & (reviews['2starratio']>reviews['3starratio']) & (reviews['2starratio']>reviews['4starratio']) & (reviews['2starratio']>reviews['5starratio'])]
threestar = reviews[(reviews['3starratio']>reviews['1starratio']) & (reviews['3starratio']>reviews['2starratio']) & (reviews['3starratio']>reviews['4starratio']) & (reviews['3starratio']>reviews['5starratio'])]
fourstar = reviews[(reviews['4starratio']>reviews['1starratio']) & (reviews['4starratio']>reviews['2starratio']) & (reviews['4starratio']>reviews['3starratio']) & (reviews['4starratio']>reviews['5starratio'])]
fivestar = reviews[(reviews['5starratio']>reviews['1starratio']) & (reviews['5starratio']>reviews['2starratio']) & (reviews['5starratio']>reviews['3starratio']) & (reviews['5starratio']>reviews['4starratio'])]

In [330]:
onetop = onestar.sort_values('1starratio',ascending=False)
onetop.head()

1starcount  2starcount  3starcount  4starcount  5starcount  \
Token                                                                  
minutes     1.315603    1.158730    1.082117    1.046934    1.037525   
told        1.248227    1.116883    1.045620    1.033687    1.036327   
asked       1.244681    1.155844    1.062956    1.044285    1.039122   
said        1.258865    1.180375    1.114964    1.078350    1.061078   
horrible    1.136525    1.027417    1.010949    1.004921    1.002794   

          1starratio  2starratio  3starratio  4starratio  5starratio  
Token                                                                 
minutes     0.304164    0.258519    0.237369    0.227893    0.225383  
told        0.294914    0.255939    0.235759    0.232443    0.233175  
asked       0.289312    0.263228    0.237059    0.231929    0.230518  
said        0.283863    0.261535    0.243513    0.233648    0.229048  
horrible    0.280895    0.247261    0.242338    0.240545    0.239914

In [331]:
twotop = twostar.sort_values('2starratio',ascending=False)
twotop.head()

1starcount  2starcount  3starcount  4starcount  5starcount  \
Token                                                                
like      1.588652    1.734488    1.592153    1.504921    1.372455   
just      1.588652    1.643579    1.570255    1.418244    1.371657   
food      1.783688    1.822511    1.689781    1.617714    1.508583   
better    1.182624    1.266955    1.211679    1.138910    1.106188   
really    1.253546    1.417027    1.396898    1.372067    1.271856   

        1starratio  2starratio  3starratio  4starratio  5starratio  
Token                                                               
like      0.256068    0.286305    0.256778    0.239342    0.213771  
just      0.264611    0.276287    0.260747    0.229707    0.220498  
food      0.268685    0.276148    0.250989    0.237740    0.218202  
better    0.250358    0.273086    0.258096    0.238893    0.230448  
really    0.229678    0.267648    0.262847    0.256974    0.233817

In [332]:
threetop = threestar.sort_values('3starratio',ascending=False)
threetop.head()

1starcount  2starcount  3starcount  4starcount  5starcount  \
Token                                                                
good      1.429078    1.672439    1.897810    1.837245    1.489421   
pretty    1.088652    1.180375    1.291971    1.234292    1.093812   
ok        1.076241    1.170274    1.177920    1.051855    1.027146   
think     1.150709    1.193362    1.250912    1.155185    1.100200   
little    1.115248    1.174603    1.278285    1.271764    1.165269   

        1starratio  2starratio  3starratio  4starratio  5starratio  
Token                                                               
good      0.207205    0.251360    0.295233    0.283143    0.217861  
pretty    0.226781    0.250678    0.281038    0.265165    0.228101  
ok        0.243098    0.270074    0.272319    0.236288    0.229464  
think     0.244849    0.256251    0.271970    0.246036    0.231613  
little    0.228071    0.243161    0.270429    0.268678    0.240763

In [333]:
fourtop = fourstar.sort_values('4starratio',ascending=False)
fourtop.head()

1starcount  2starcount  3starcount  4starcount  5starcount  \
Token                                                                    
great         1.115248    1.259740    1.381387    1.636260    1.613573   
nice          1.109929    1.178932    1.270985    1.276684    1.180439   
definitely    1.037234    1.060606    1.115876    1.153671    1.109780   
fresh         1.046099    1.060606    1.105839    1.153293    1.142116   
tasty         1.012411    1.063492    1.108577    1.123013    1.063074   

            1starratio  2starratio  3starratio  4starratio  5starratio  
Token                                                                   
great         0.189315    0.219220    0.245588    0.304707    0.299218  
nice          0.226191    0.243680    0.267802    0.269326    0.244067  
definitely    0.233615    0.240143    0.255859    0.266838    0.254106  
fresh         0.234454    0.238481    0.251206    0.264841    0.261603  
tasty         0.232303    0.246917    0.260108    0.264390    0.246796

In [334]:
fivetop = fivestar.sort_values('5starratio',ascending=False)
fivetop.head()

1starcount  2starcount  3starcount  4starcount  5starcount  \
Token                                                                   
love         1.058511    1.098124    1.164234    1.219531    1.333333   
best         1.097518    1.119769    1.113139    1.175246    1.299401   
amazing      1.023050    1.031746    1.051095    1.095004    1.187226   
delicious    1.040780    1.051948    1.067518    1.171461    1.176846   
favorite     1.010638    1.028860    1.055657    1.095382    1.133733   

           1starratio  2starratio  3starratio  4starratio  5starratio  
Token                                                                  
love         0.219826    0.229944    0.247210    0.262028    0.293660  
best         0.233140    0.238996    0.237245    0.253842    0.288392  
amazing      0.234372    0.236836    0.242354    0.255060    0.282613  
delicious    0.232953    0.236042    0.240376    0.270103    0.271682  
favorite     0.234289    0.239525    0.247307    0.259024    0.270546

In [335]:
reviews.loc['love']

1starcount    1.058511
2starcount    1.098124
3starcount    1.164234
4starcount    1.219531
5starcount    1.333333
1starratio    0.219826
2starratio    0.229944
3starratio    0.247210
4starratio    0.262028
5starratio    0.293660
Name: love, dtype: float64